# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0dd7db37bbe35d1549c413a0acbea118bada721e74f260900529b54a050e3b70fb6cd072fd658daa2b2a2a2ba2bc1888308c8e28b9e7a4169197ddbc868fd56

test:
  secret_key_base: be1e3ee5117e7de877e65b77b7c9f0dbd7ea8194c1cff3f81aec54fae11ad933fa3a235dea626f7c6d4ff7532e48579a5f76544924318428d859e222a348109a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
